data = [
    {'name': 'Ayeza Khan', 'follower_count': 14.1, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Aiman Khan', 'follower_count': 12.7, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Mahira Khan', 'follower_count': 11.6, 'description': 'Actress and film star', 'country': 'Pakistan'},
    {'name': 'Sarah Khan', 'follower_count': 11.2, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Sajal Aly', 'follower_count': 10.6, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Maya Ali', 'follower_count': 9.8, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Iqra Aziz', 'follower_count': 9.3, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Hania Aamir', 'follower_count': 8.3, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Kinza Hashmi', 'follower_count': 7.7, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Minal Khan', 'follower_count': 7.6, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Urwa Hocane', 'follower_count': 6.8, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Zara Noor Abbas', 'follower_count': 5.9, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Sanam Baloch', 'follower_count': 5.7, 'description': 'Actress and host', 'country': 'Pakistan'},
    {'name': 'Saba Qamar', 'follower_count': 4.6, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Yumna Zaidi', 'follower_count': 3.7, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Mehwish Hayat', 'follower_count': 3.0, 'description': 'Actress and film star', 'country': 'Pakistan'},
    {'name': 'Humaima Malick', 'follower_count': 1.8, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Ayesha Omar', 'follower_count': 1.7, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Sanam Jung', 'follower_count': 1.4, 'description': 'Actress and host', 'country': 'Pakistan'},
    {'name': 'Momina Mustehsan', 'follower_count': 2.8, 'description': 'Singer and songwriter', 'country': 'Pakistan'},
    {'name': 'Hadiqa Kiani', 'follower_count': 1.1, 'description': 'Singer and philanthropist', 'country': 'Pakistan'},
    {'name': 'Sadaf Kanwal', 'follower_count': 1.2, 'description': 'Model and actress', 'country': 'Pakistan'},
    {'name': 'Amna Ilyas', 'follower_count': 0.8, 'description': 'Model and actress', 'country': 'Pakistan'},
    {'name': 'Jannat Mirza', 'follower_count': 20.0, 'description': 'TikTok star', 'country': 'Pakistan'},
    {'name': 'Kanwal Aftab', 'follower_count': 15.0, 'description': 'TikTok star', 'country': 'Pakistan'},
    {'name': 'Bushra Ansari', 'follower_count': 1.2, 'description': 'Actress, singer, and writer', 'country': 'Pakistan'},
    {'name': 'Reema Khan', 'follower_count': 1.0, 'description': 'Actress and film star', 'country': 'Pakistan'},
    {'name': 'Nadia Khan', 'follower_count': 0.9, 'description': 'Actress and morning show host', 'country': 'Pakistan'},
    {'name': 'Samina Peerzada', 'follower_count': 0.8, 'description': 'Veteran actress and host', 'country': 'Pakistan'},
    {'name': 'Mahnoor Baloch', 'follower_count': 0.7, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Annie Khalid', 'follower_count': 0.6, 'description': 'Singer', 'country': 'Pakistan'},
    {'name': 'Noor Bukhari', 'follower_count': 0.5, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Neelam Muneer', 'follower_count': 2.5, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Ayesha Khan', 'follower_count': 2.2, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Sonya Hussyn', 'follower_count': 2.1, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Armeena Khan', 'follower_count': 1.5, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Resham', 'follower_count': 1.0, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Meesha Shafi', 'follower_count': 0.9, 'description': 'Singer and actress', 'country': 'Pakistan'},
    {'name': 'Hira Mani', 'follower_count': 6.0, 'description': 'Actress and host', 'country': 'Pakistan'},
    {'name': 'Sanam Saeed', 'follower_count': 3.9, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Shaniera Akram', 'follower_count': 0.6, 'description': 'Philanthropist and activist', 'country': 'Pakistan'},
    {'name': 'Anoushey Ashraf', 'follower_count': 0.7, 'description': 'TV host and VJ', 'country': 'Pakistan'},
    {'name': 'Mehreen Syed', 'follower_count': 0.5, 'description': 'Model and entrepreneur', 'country': 'Pakistan'},
    {'name': 'Syra Yousuf', 'follower_count': 2.0, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Mashal Khan', 'follower_count': 1.4, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Komal Aziz Khan', 'follower_count': 1.3, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Sohai Ali Abro', 'follower_count': 1.1, 'description': 'Actress and dancer', 'country': 'Pakistan'},
    {'name': 'Eman Suleman', 'follower_count': 0.4, 'description': 'Model and activist', 'country': 'Pakistan'},
    {'name': 'Ainy Jaffri', 'follower_count': 0.5, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Sehar Khan', 'follower_count': 1.2, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Dur-e-Fishan Saleem', 'follower_count': 1.1, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Hiba Bukhari', 'follower_count': 1.0, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Momal Sheikh', 'follower_count': 0.9, 'description': 'Actress and producer', 'country': 'Pakistan'},
    {'name': 'Nimra Khan', 'follower_count': 0.8, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Anmol Baloch', 'follower_count': 0.7, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Areeba Habib', 'follower_count': 0.7, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Alizeh Shah', 'follower_count': 2.0, 'description': 'Actress and model', 'country': 'Pakistan'},
    {'name': 'Ramsha Khan', 'follower_count': 1.4, 'description': 'Actress', 'country': 'Pakistan'},
    {'name': 'Syeda Tuba Anwar', 'follower_count': 0.6, 'description': 'Actress and host', 'country': 'Pakistan'},
    {'name': 'Natasha Ali', 'follower_count': 0.5, 'description': 'Actress and makeup artist', 'country': 'Pakistan'},
    {'name': 'Sharmeen Obaid Chinoy', 'follower_count': 0.4, 'description': 'Oscar-winning filmmaker', 'country': 'Pakistan'},
    {'name': 'Samina Ahmed', 'follower_count': 0.3, 'description': 'Veteran actress', 'country': 'Pakistan'},
    {'name': 'Atiqa Odho', 'follower_count': 0.3, 'description': 'Actress and entrepreneur', 'country': 'Pakistan'},
    {'name': 'Yasir Nawaz', 'follower_count': 0.8, 'description': 'Actor, director, and host', 'country': 'Pakistan'},
    {'name': 'Sami Khan', 'follower_count': 0.7, 'description': 'Actor', 'country': 'Pakistan'},
    {'name': 'Affan Waheed', 'follower_count': 0.9, 'description': 'Actor and RJ', 'country': 'Pakistan'},
    {'name': 'Adeel Hussain', 'follower_count': 0.6, 'description': 'Actor and director', 'country': 'Pakistan'},
    {'name': 'Mohib Mirza', 'follower_count': 0.5, 'description': 'Actor and host', 'country': 'Pakistan'},
    {'name': 'Ali Kazmi', 'follower_count': 0.4, 'description': 'Actor and model', 'country': 'Pakistan'},
    {'name': 'Adnan Malik', 'follower_count': 0.4, 'description': 'Actor and producer', 'country': 'Pakistan'},
    {'name': 'Gohar Rasheed', 'follower_count': 0.5, 'description': 'Actor', 'country': 'Pakistan'},
    {'name': 'Jibran Nasir', 'follower_count': 0.6, 'description': 'Lawyer and activist', 'country': 'Pakistan'},
    {'name': 'Ali Azmat', 'follower_count': 0.6, 'description': 'Singer (Junoon)', 'country': 'Pakistan'},
    {'name': 'Salman Ahmed', 'follower_count': 0.5, 'description': 'Musician (Junoon)', 'country': 'Pakistan'},
    {'name': 'Abrar-ul-Haq', 'follower_count': 0.7, 'description': 'Singer and politician', 'country': 'Pakistan'},
    {'name': 'Jawad Ahmad', 'follower_count': 0.4, 'description': 'Singer and activist', 'country': 'Pakistan'},
    {'name': 'Ali Noor', 'follower_count': 0.4, 'description': 'Singer (Noori)', 'country': 'Pakistan'},
    {'name': 'Ali Hamza', 'follower_count': 0.3, 'description': 'Singer (Noori)', 'country': 'Pakistan'},
    {'name': 'Imran Khan', 'follower_count': 10.9, 'description': 'Former Prime Minister and cricketer', 'country': 'Pakistan'},
    {'name': 'Atif Aslam', 'follower_count': 9.4, 'description': 'Singer and musician', 'country': 'Pakistan'},
    {'name': 'Danish Taimoor', 'follower_count': 8.7, 'description': 'Actor and host', 'country': 'Pakistan'},
    {'name': 'Ali Zafar', 'follower_count': 8.2, 'description': 'Singer and actor', 'country': 'Pakistan'},
    {'name': 'Bilal Abbas Khan', 'follower_count': 6.9, 'description': 'Actor', 'country': 'Pakistan'},
    {'name': 'Farhan Saeed', 'follower_count': 6.2, 'description': 'Singer and actor', 'country': 'Pakistan'},
    {'name': 'Humayun Saeed', 'follower_count': 4.8, 'description': 'Actor and producer', 'country': 'Pakistan'},
    {'name': 'Adnan Siddiqui', 'follower_count': 4.1, 'description': 'Actor and producer', 'country': 'Pakistan'},
    {'name': 'Sheheryar Munawar', 'follower_count': 5.2, 'description': 'Actor and producer', 'country': 'Pakistan'},
    {'name': 'Ali Rehman Khan', 'follower_count': 3.3, 'description': 'Actor', 'country': 'Pakistan'},
    {'name': 'Feroze Khan', 'follower_count': 3.1, 'description': 'Actor', 'country': 'Pakistan'},
    {'name': 'Imran Abbas', 'follower_count': 2.9, 'description': 'Actor and model', 'country': 'Pakistan'},
    {'name': 'Fawad Khan', 'follower_count': 1.6, 'description': 'Actor and singer', 'country': 'Pakistan'},
    {'name': 'Junaid Khan', 'follower_count': 1.5, 'description': 'Actor and singer', 'country': 'Pakistan'},
    {'name': 'Ali Safina', 'follower_count': 1.9, 'description': 'Actor and host', 'country': 'Pakistan'},
    {'name': 'Asim Azhar', 'follower_count': 2.7, 'description': 'Singer', 'country': 'Pakistan'},
    {'name': 'Ali Gul Pir', 'follower_count': 1.3, 'description': 'Comedian and rapper', 'country': 'Pakistan'},
    {'name': 'Shahid Afridi', 'follower_count': 2.6, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Babar Azam', 'follower_count': 2.5, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Wasim Akram', 'follower_count': 2.1, 'description': 'Former cricketer', 'country': 'Pakistan'},
    {'name': 'Shoaib Malik', 'follower_count': 2.0, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Mohammad Rizwan', 'follower_count': 1.7, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Shaheen Shah Afridi', 'follower_count': 1.6, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Haris Rauf', 'follower_count': 1.3, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Sarfaraz Ahmed', 'follower_count': 1.0, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Shan Masood', 'follower_count': 0.9, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Hasan Ali', 'follower_count': 0.8, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Wahab Riaz', 'follower_count': 0.7, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Irfan Junejo', 'follower_count': 0.7, 'description': 'YouTuber and vlogger', 'country': 'Pakistan'},
    {'name': 'Shahveer Jafry', 'follower_count': 0.6, 'description': 'YouTuber and comedian', 'country': 'Pakistan'},
    {'name': 'Zaid Ali T', 'follower_count': 0.5, 'description': 'YouTuber and comedian', 'country': 'Pakistan'},
    {'name': 'Rahim Pardesi', 'follower_count': 0.4, 'description': 'Comedian and content creator', 'country': 'Pakistan'},
    {'name': 'Nadir Ali', 'follower_count': 0.3, 'description': 'Comedian (P4 Pakao)', 'country': 'Pakistan'},
    {'name': 'Wasim Badami', 'follower_count': 0.9, 'description': 'News anchor', 'country': 'Pakistan'},
    {'name': 'Hamza Ali Abbasi', 'follower_count': 1.2, 'description': 'Actor and activist', 'country': 'Pakistan'},
    {'name': 'Ahmed Ali Butt', 'follower_count': 0.6, 'description': 'Comedian and actor', 'country': 'Pakistan'},
    {'name': 'Moammar Rana', 'follower_count': 0.5, 'description': 'Actor and film star', 'country': 'Pakistan'},
    {'name': 'Ahsan Khan', 'follower_count': 1.0, 'description': 'Actor and host', 'country': 'Pakistan'},
    {'name': 'Azfar Rehman', 'follower_count': 0.8, 'description': 'Actor and host', 'country': 'Pakistan'},
    {'name': 'Mikaal Zulfiqar', 'follower_count': 1.1, 'description': 'Actor and model', 'country': 'Pakistan'},
    {'name': 'Nouman Ijaz', 'follower_count': 0.9, 'description': 'Veteran actor', 'country': 'Pakistan'},
    {'name': 'Saud Qasmi', 'follower_count': 0.4, 'description': 'Actor and producer', 'country': 'Pakistan'},
    {'name': 'Fakhar Zaman', 'follower_count': 0.8, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Imam-ul-Haq', 'follower_count': 0.7, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Umar Akmal', 'follower_count': 0.6, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Kamran Akmal', 'follower_count': 0.5, 'description': 'Cricketer', 'country': 'Pakistan'},
    {'name': 'Yasir Hussain', 'follower_count': 0.7, 'description': 'Actor and comedian', 'country': 'Pakistan'},
    {'name': 'Javed Miandad', 'follower_count': 0.3, 'description': 'Legendary cricketer', 'country': 'Pakistan'},
    {'name': 'Inzamam-ul-Haq', 'follower_count': 0.4, 'description': 'Legendary cricketer', 'country': 'Pakistan'},
    {'name': 'Shoaib Akhtar', 'follower_count': 1.5, 'description': 'Former cricketer', 'country': 'Pakistan'}
]
